### ISSUE TITLE
Team 16: Invalid IP Address crashes the app

### ISSUE THREAD

**Issue by marceloarchiza** [byucs340ta/Fall2018#10]
1. Start server on 127.0.0.1
2. Start app
3. Fill out username and password
4. Add IP: 127.0.0.1 (instead of 10.0.2.2)
**Expected Result:** "Invalid IP Address" error message pops up
**Actual Result**: App crashes

#Team16
#Phase3

**Comment by xaque** [comment]
Resolved.
