### ISSUE TITLE
No Display for cards left in Train Card or Destination Card Decks

### ISSUE THREAD

**Issue by jakegriffey** [byucs340ta/Fall2018#103]
Doesn't tell you how many cards are in either of the decks.

**Comment by jakegriffey** [comment]
To clarify, it doesn't tell you how many cards are remaining in the decks

**Comment by drakebw** [comment]
We added the display to the train card deck but don't feel it is necessary to do so for the destination card deck. Doing so would cause significant design issues that are not frankly worth something that is only aesthetic.
