### ISSUE TITLE
Temporary Chat Disapperance

### ISSUE THREAD

**Issue by jakegriffey** [byucs340ta/Fall2018#105]
If you leave the chat page, go to destination cards, and then go back to chat, 
all the messages disappear until someone sends another message, and then all of them reappear.

It may not always be that exact sequence but if you send some messages in chat, close the drawer and take some turns, the messages are all gone when you come back until someone sends a new one

**Comment by jakegriffey** [comment]
Added the labels

**Comment by Serryx** [comment]
Should be fixed now.
