### ISSUE TITLE
start game error

### ISSUE THREAD

**Issue by BrainRayChristensen** [byucs340ta/Fall2018#144]
Game will sometimes crash for one user on game start. You can see this by having users join a game, and starting a game

**Comment by marceloarchiza** [comment]
How many users did you have when you repro this bug? Can you give better steps to reproduce this bug?

**Comment by BrainRayChristensen** [comment]
i can't give better steps because it only happened occasionally. We started the game from scratch, (we restarted the app, and created a game and joined it and then started it) We usually did it with just two people and occasionally one person's game would crash.

**Comment by marceloarchiza** [comment]
Sweet! We had a bug like this before that we fixed. It was some kind of null check. We will repro these steps a few times to see if we can repro. Thanks!

**Comment by marceloarchiza** [comment]
We are not being able to repro it. We have been using for a while and it never happens. Unable to repro, so closing it.
