### ISSUE TITLE
Team 16: Logged In As "Null"

### ISSUE THREAD

**Issue by Fourty-Too** [byucs340ta/Fall2018#15]
1. Start Server on 127.0.0.1
2. Start Game on 2 devices (Device A and Device B)
3. Log into both devices
4. Create a game on Device A
5. Enter game on Device B
6. Exit Game on Device B
     **Expected Result:** Device B will display a Toast with the correct username/no toast displayed
     **Actual Result:** Device B displays a Toast with the text "Logged In As null"

#Team 16
#Phase 3

**Comment by xaque** [comment]
Fixed.
