### ISSUE TITLE
Getting to the end of the game

### ISSUE THREAD

**Issue by breanna-pace** [byucs340ta/Fall2018#152]
Expected:
	Game can end when players claim enough routes.
Actual:
	I haven’t been able to reach the game end because the claiming of routes is not working sufficiently.

**Comment by katiecs3** [comment]
What do you mean by "not working sufficiently?"

**Comment by breanna-pace** [comment]
For me, it always shows an error when I try to claim, either that the cards are wrong or that there’s an unknown error. Some of my team mates were able to claim paths, though it didn’t show much feedback other than the points changing. I couldn’t get to the end of the game since the only way to run out of train pieces is to claim enough routes.
