### ISSUE TITLE
Changing turns after selecting face-up train cards

### ISSUE THREAD

**Issue by breanna-pace** [byucs340ta/Fall2018#154]
Expected:
	After selecting 2 face-up train cards on my turn, the turn indicator at the top should change.
Actual:
	It does change eventually, but it takes several seconds to first remove the current highlight, then add the correct one. When my devices were running slower, it looked like it wasn’t changing at all.

**Comment by katiecs3** [comment]
This is an issue with running in an emulator, not an issue with the code. The emulators are just slow, especially if you are using 2 emulators.
