### ISSUE TITLE
Select Destination Cards on my turn

### ISSUE THREAD

**Issue by breanna-pace** [byucs340ta/Fall2018#156]
Expected:
	Select at least one destination card, return to previous screen (or show that it was successful). Display new destination cards.
Actual:
	I can click on the destination cards, and the “Select Cards” button correctly is only shown if I have selected one or more, but the button does not seem to do anything.
Update: 
	I think it appears to not do anything because the changing of turns takes a long time. If there was a toast saying the selection is successful, and/or if it closed back out to the map view, that would make it clearer.

**Comment by katiecs3** [comment]
Did you have this problem every time you tried to draw destination cards (on your turn)?

**Comment by breanna-pace** [comment]
Yes. The button might be working as far as assigning me the destination cards, but there wasn't any visual indication that it did anything.

**Comment by cameronconradt** [comment]
Missing bracket caused massive slowdown, fixed now
