### ISSUE TITLE
Selecting D card page is ugly

### ISSUE THREAD

**Issue by BrainRayChristensen** [byucs340ta/Fall2018#159]
The page for selecting D cards is ugly... it looks very unfinished and out of character compared to the rest of the app.

**Comment by emmettito** [comment]
Is this a bug? lol

**Comment by marceloarchiza** [comment]
hahahahaah

**Comment by marceloarchiza** [comment]
hahahah

**Comment by Thecooljason** [comment]
We changed the background, but this shouldn't have been logged.

**Comment by Thecooljason** [comment]
We changed the background, but this is not a lab requirement and should not have been logged.
