### ISSUE TITLE
Game started while lobby doesnt have enough active users

### ISSUE THREAD

**Issue by haoyucn** [byucs340ta/Fall2018#184]
Game is still starting without enough active users.

In one case, the host user of a game (max player 2) turn off the app and log in with another account, game still automatically start after a new player join in the game.

**Comment by kwolfe2** [comment]
We designed it this way purposely. We decided that each user can only be in one game or lobby at a time, so even when they log out they are still in that game/lobby. You can still log back into the host's account and join the game that started, even though the host wasn't watching when it started.
