### ISSUE TITLE
Crash claiming St. Louis to Nashville

### ISSUE THREAD

**Issue by SponJ2000** [byucs340ta/Fall2018#187]
Game client crashed when trying to claim Saint Louis to Nashville. Had ~10 trains left.

Player 2 attempts to claim Saint Louis to Nashville, Player 2 client crashes. It's now Player 1's turn.
Player 1 attempts to claim Saint Louis to Nashville (to recreate bug). Player 1 client also crashes.

Edit 1: Claiming it at the beginning of the game works fine, so it may be related to the state of the game

**Comment by SponJ2000** [comment]
Edit 2: This is probably tied to the bug that causes the game to crash when entering the final round.

**Comment by jacobgropp** [comment]
This is now fixed. The game must have ended and crashed then. We could not create any issue with this specific route.
