### ISSUE TITLE
Routes hard to select

### ISSUE THREAD

**Issue by SponJ2000** [byucs340ta/Fall2018#188]
It's hard to select routes (sometimes you have to tap a bit to the right or left), especially in the case of dual routes.

**Comment by Mimikyu778** [comment]
We see this issue and will address it after fixing P3-P1 bugs

**Comment by Mimikyu778** [comment]
We attempted to adjust the hitboxes of markers and lines, etc., but Google limits what we can do with that. We can't even remove clickablility on markers in the map... So unfortunately that will be the nature of the map
