### ISSUE TITLE
Error tracking players remainig train cars

### ISSUE THREAD

**Issue by SponJ2000** [byucs340ta/Fall2018#191]
Sometimes, the remaining train cars don't update between clients, leading to different totals on different phones.

Edit 1: This can go both ways it seems. Sometimes, the train car total isn't updated, while other times the train car total is decreased too much. This may or may not lead to the problems when entering the "final round."

**Comment by kwolfe2** [comment]
Server wasn't sending right number of train cars to each client (was sending each client their own number)
