### ISSUE TITLE
There are times where you cannot see which cards you have in your hand, they are all face down

### ISSUE THREAD

**Issue by tbarton18** [byucs340ta/Fall2018#194]

**Comment by BrainRayChristensen** [comment]
what activity was this in? was this when making a route? because if so, that was intentional. Cards that cannot be used to make the route should not be availible to be clicked on.

**Comment by BrainRayChristensen** [comment]
@tbarton18 sooooo....

**Comment by tbarton18** [comment]
It was view your personal information. I never did see it after that though, so it might have been a fluke with connecting to the server wrong.

**Comment by RyanRemer** [comment]
alright thanks man!

**Comment by BrainRayChristensen** [comment]
could not replicate
