### ISSUE TITLE
Cannot claim grey routes

### ISSUE THREAD

**Issue by jacobgropp** [byucs340ta/Fall2018#200]
No option to claim a grey route. When it is clicked on you have no option to choose which card if any you would like to use.

**Comment by SponJ2000** [comment]
If you have enough cards, double clicking the route marker will take you to a page where you can choose the color of card. If you don't have enough, then nothing happens.

I just tested it now and it works fine.

**Comment by jacobgropp** [comment]
Awesome, now I see. I was clicking in the wrong spot. Once you guys have the toasts showing up like planned that will make more sense. Nice!
