### ISSUE TITLE
Shows wrong information about the number of train cards

### ISSUE THREAD

**Issue by haoyucn** [byucs340ta/Fall2018#201]
The red player and blue player should have 6 cards
![bug3](https://user-images.githubusercontent.com/31866194/49122254-e8281500-f270-11e8-9709-4fed2543b42d.png)

**Comment by SponJ2000** [comment]
I've noticed that when someone draws a card face-up, the other player shows them getting two cards instead of one. This doesn't seem to happen when drawing from the deck.

**Comment by kwolfe2** [comment]
Fixed with fixing the claim route changing card amounts bug
