### ISSUE TITLE
Some train cards are added when claiming a gray route

### ISSUE THREAD

**Issue by haoyucn** [byucs340ta/Fall2018#204]
I tried claiming a gray route using green train card + locomotive card, and the red train card is being added

![traincard](https://user-images.githubusercontent.com/31866194/49122384-73a1a600-f271-11e8-8916-d1c09228b34b.png)
![traincard2](https://user-images.githubusercontent.com/31866194/49122386-74d2d300-f271-11e8-9327-0d083b1018e8.png)

**Comment by kwolfe2** [comment]
Recreated bug and looked at logs. I still don't know the cause, but it looks like server and client had different hands for the player. I claimed a grey route of length 2, intending to use 1 purple card and 1 locomotive. The player's hand before the turn: 
![image](https://user-images.githubusercontent.com/28762596/49186980-54635100-f323-11e8-84dd-ce004818d699.png)
The player's hand after the turn:
![image](https://user-images.githubusercontent.com/28762596/49186999-634a0380-f323-11e8-8186-fbc6d0126713.png)
The server had the hand with two purple cards:
greenCard
redCard
yellowCard
yellowCard
purpleCard
whiteCard
locomotive
redCard
redCard
whiteCard
orangeCard
greenCard
blueCard
greenCard
blackCard
blueCard
whiteCard
redCard
blackCard
yellowCard
orangeCard
orangeCard
yellowCard
blueCard
locomotive
blackCard
greenCard
whiteCard
purpleCard
blackCard
yellowCard
orangeCard
locomotive
yellowCard
whiteCard
locomotive

**Comment by kwolfe2** [comment]
Fixed the bug. The problem was on drawing from face up, the draw card from deck function was also adding the card to a user. When the server drew from the deck to replenish the face up cards, it both added that card to the face up cards and the user that drew. Fixing this also fixed the card numbers on the player info not updating right bug
