### ISSUE TITLE
Entering last round crashes game

### ISSUE THREAD

**Issue by SponJ2000** [byucs340ta/Fall2018#208]
3 games in a row, claiming a route that would put the game in the last round crashes the client.

**Comment by kwolfe2** [comment]
Recreated bug. Trying to claim the route is throwing a null pointer exception on line 96 of GameDAO.

**Comment by kwolfe2** [comment]
It at least doesn't crash now. It doesn't appear to end the game either

**Comment by kwolfe2** [comment]
Need to fix server detection of end game. Also it might not be checking if you have enough cards in the client

**Comment by kwolfe2** [comment]
End game is now working properly
