### ISSUE TITLE
Server speed bug

### ISSUE THREAD

**Issue by icleen** [byucs340ta/Fall2018#211]
So when you get into the late game your server is taking a long time to respond, meaning that there is a long gap when it is neither player's turn and nothing can happen.  We believe this to be caused by the fact that the server is calculating whether a route has been complete every round.  It is also calculating longest path after every move.  Both of these things only need to be calculated once at the end of the game.

**Comment by jacobgropp** [comment]
The claimRoute function was drawing polylines on top of each other everytime the view updated causing a huge lag in the GoogleMap. This has since been fixed.
