### ISSUE TITLE
Face up cards blocked by UI and isn't scrollable so only 3 face up cards are visible

### ISSUE THREAD

**Issue by cameronconradt** [byucs340ta/Fall2018#242]
This was using the Nexus 7 Emulator which is a tablet, but is only 1080p I believe so you might not have issues on bigger screens

![image](https://user-images.githubusercontent.com/16780811/49126734-0a765e80-f282-11e8-8ee7-486dcff5af67.png)

**Comment by andrewblomquist** [comment]
A fix has been implemented an a merge request submitted.
