### ISSUE TITLE
Chat textbox doesn't clear on send

### ISSUE THREAD

**Issue by cameronconradt** [byucs340ta/Fall2018#245]
This is mostly an annoyance rather than anything because you have to clear the textbox to send a new message. Also the text display only is 2/3 of the screen for some reason.

![image](https://user-images.githubusercontent.com/16780811/49127325-1ebb5b00-f284-11e8-8629-6315b44c3aa9.png)

**Comment by andrewblomquist** [comment]
fixed and merge request submitted
