### ISSUE TITLE
"most routes" award rewarded improperly

### ISSUE THREAD

**Issue by HunterRasmussen** [byucs340ta/Fall2018#277]
Start a game with two players.  After claiming destination cards, end the game.  Most routes is awarded to a player even though no routes are claimed.

**Comment by andrewblomquist** [comment]
Did both players have zero routes claimed?  Because then that's just a tie being broken and the system giving one of the players the award.

**Comment by HunterRasmussen** [comment]
Ah yes.  Didn't realize that was the intended case

**Comment by andrewblomquist** [comment]
No worries. I can look into making that more clear to the players.
