### ISSUE TITLE
Game History shows non-existent history

### ISSUE THREAD

**Issue by HunterRasmussen** [byucs340ta/Fall2018#278]
Start a new game with two players.  Perform a couple actions.  End the game.  Create a new game with two players.  Note that history shows game actions that didn’t happen (mine showed claiming 8 train cards which might just be the start out deal but it also shows that someone claimed a path)

**Comment by andrewblomquist** [comment]
Players may not be properly detaching from a finished game. Those history items seen in game 2 could have been the actions taken in game 1.

**Comment by andrewblomquist** [comment]
Currently assuming #279 stems from the same issue this ticket has.

**Comment by andrewblomquist** [comment]
Also assuming #280 has the same problem.

**Comment by andrewblomquist** [comment]
Players are now properly detached from a game, and all three tickets have been resolved.
