### ISSUE TITLE
Player Train Card count shows up incorrectly.

### ISSUE THREAD

**Issue by HunterRasmussen** [byucs340ta/Fall2018#280]
Start a game with two players and draw a handful of train cards with both players.  End the game using the endgame button, then close it and remove from recents on both players.  Relaunch and login with the same two players.  Start a new game.  After picking destination cards click the player specs button and note that the amount of train cards for each player isn’t the default 4.

**Comment by andrewblomquist** [comment]
If it wasn't the default 4, what was it?

**Comment by HunterRasmussen** [comment]
It was however many were drawn in the previous game.  

For instance.  If I start a game and draw 10 cards, then follow the steps above, the next game I start or join shows me as having 14 cards

**Comment by andrewblomquist** [comment]
Looks like it is probably tied to the referenced ticket then. Thanks!!
