### ISSUE TITLE
Trying to create a game with duplicate name of ended game results in empty toast

### ISSUE THREAD

**Issue by HunterRasmussen** [byucs340ta/Fall2018#281]
Start a game with two players naming the game “hey”.  Draw destination cards then click the end game button on both players.  Close the app and clear it from recents.  relaunch and log back in with one of the same players. Try to create a game called “hey”.  Note an empty toast at the bottom

**Comment by andrewblomquist** [comment]
Sounds like we're not properly clearing out a finished game from memory.  We ended up using game names as primary keys, so I'm willing to bet that's why the 2nd game couldn't create correctly.

**Comment by andrewblomquist** [comment]
This has been fixed.
