### ISSUE TITLE
Owner Re-joining a Game

### ISSUE THREAD

**Issue by andrewblomquist** [byucs340ta/Fall2018#83]
This one is kinda silly - only found it because my emulator crashed. Feel free to ignore this one too, it may be outside the scope of the project anyway.

Let's say "Player 1" logged in and created a game. Then for whatever reason (an emulator crash, for example), "Player 1" leaves the application and comes back. They log in and see the game they created earlier still up and waiting for players. They re-join their game.

Instead of the application realizing the original host is re-joining, "Player 1" is added to the game as a second player. Meaning the player list for the game now has "Player 1" listed twice. The application still lets them start the game, but gameplay halts because "Player 1" can't chose an opening destination hand twice.

**Comment by cameronconradt** [comment]
User now is given the original playerID instead of a new one being generated
