### ISSUE TITLE
Rejoining a game after backing out

### ISSUE THREAD

**Issue by neilsduncan** [byucs340ta/Fall2018#96]
Using the back arrow a player can leave the game and then rejoin using the game waiting screen they will eventually arrive at if the button is pushed several times. Form this screen they are able to rejoin but do not enter the game as their previous player. They join as a new player mid game starting with no cards but get to choose destination cards as if it were still in set up.

The second player to do this also rejoins as a new player but does not get chose train cards.

This may also cause problems with turn order but that was left untested due to number of emulator limitations.

**Comment by cameronconradt** [comment]
User now is given the original playerID instead of a new one being generated
