### ISSUE TITLE
Multiple routes are not claimable by the colors displayed on the board

### ISSUE THREAD

**Issue by neilsduncan** [byucs340ta/Fall2018#97]
Routes tested to do this are:
Atlanta-Miami
Phoenix-Denver
Montreal- Any

Others appeared during testing but those are the only ones written down.

**Comment by andrewblomquist** [comment]
Calgary - Helena was one that I encountered.

**Comment by katiecs3** [comment]
With these, are you sure that you selected the correct route - the routes are small and if you hit the incorrect route you may not have noticed and would get this error.

**Comment by andrewblomquist** [comment]
Yes, I believe I was selecting the correct route. The app seemed to care if I clicked on a dash in the line or not, so I began trying to be as precise as I could.
